# Supply Chain Forecast — Data Loader

Pulls `model_ready_dense_data` from Supabase via **Polars** and reshapes it
from wide format into the **NeuralForecast long format** `(unique_id, ds, y)`.

Each non-date column becomes its own time series identified by its column name.

In [1]:
import os
from pathlib import Path

import polars as pl
from dotenv import load_dotenv

## 1. Load credentials

Reads from `forecasting/.env`.  
Make sure you have filled in `SUPABASE_PROJECT_REF` and `SUPABASE_PASSWORD`.

In [2]:
# Load .env that lives next to this notebook
_ENV_FILE = Path(".") / ".env"
load_dotenv(dotenv_path=_ENV_FILE, override=True)

supabase_ref      = os.getenv("SUPABASE_PROJECT_REF", "").strip()
supabase_password = os.getenv("SUPABASE_PASSWORD", "").strip()

# Matches interpolate_data_on_supabase.py exactly
DATABASE_URL = f"postgresql://postgres.{supabase_ref}:{supabase_password}@aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require"

print(f"Connecting as: postgres.{supabase_ref}@aws-1-us-east-1.pooler.supabase.com")

Connecting as: postgres.nglmnlhjyyywbyypyxlz@aws-1-us-east-1.pooler.supabase.com

## 2. Pull `model_ready_dense_data` from Supabase

In [3]:
print("Fetching model_ready_dense_data ...")

# Matches interpolate_data_on_supabase.py: pl.read_database_uri(query, uri, engine=...)
df_wide = pl.read_database_uri("SELECT * FROM model_ready_dense_data ORDER BY date", DATABASE_URL, engine="adbc")

print(f"Wide table shape: {df_wide.shape}")
print(f"Date range: {df_wide['date'].min()} -> {df_wide['date'].max()}")
df_wide.head()

Fetching model_ready_dense_data ...
Wide table shape: (3735, 97)
Date range: 2016-01-01 -> 2026-03-23

shape: (5, 97)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ date      ┆ fred_auto ┆ fred_crud ┆ fred_gene ┆ … ┆ wb_trade_ ┆ wb_trade_ ┆ wb_trade_ ┆ wb_trade │
│ ---       ┆ mobile_mf ┆ e_oil_pri ┆ ral_freig ┆   ┆ pct_gdp_s ┆ pct_gdp_t ┆ pct_gdp_u ┆ _pct_gdp │
│ date      ┆ g_ppi_val ┆ ces_wti_d ┆ ht_trucki ┆   ┆ gp_value  ┆ ha_value  ┆ sa_value  ┆ _vnm_val │
│           ┆ ue        ┆ ail…      ┆ ng_…      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ue       │
│           ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│           ┆ str       ┆ str       ┆ str       ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2016-01-0 ┆ 149.9     ┆ 37.13     ┆ 134.2     ┆ … ┆ 302.83965 ┆ 120.57522 ┆ 26.607962 ┆ 145.4095 │
│ 1         ┆           ┆           ┆           ┆   ┆ 6046574   ┆ 728913    ┆ 0604584   ┆ 07973118 │
│ 2016-01-0 ┆ 149.9     ┆ 37.13     ┆ 134.2     ┆ … ┆ 302.83965 ┆ 120.57522 ┆ 26.607962 ┆ 145.4095 │
│ 2         ┆           ┆           ┆           ┆   ┆ 6046574   ┆ 728913    ┆ 0604584   ┆ 07973118 │
│ 2016-01-0 ┆ 149.9     ┆ 37.13     ┆ 134.2     ┆ … ┆ 302.83965 ┆ 120.57522 ┆ 26.607962 ┆ 145.4095 │
│ 3         ┆           ┆           ┆           ┆   ┆ 6046574   ┆ 728913    ┆ 0604584   ┆ 07973118 │
│ 2016-01-0 ┆ 149.9     ┆ 36.81     ┆ 134.2     ┆ … ┆ 302.83965 ┆ 120.57522 ┆ 26.607962 ┆ 145.4095 │
│ 4         ┆           ┆           ┆           ┆   ┆ 6046574   ┆ 728913    ┆ 0604584   ┆ 07973118 │
│ 2016-01-0 ┆ 149.9     ┆ 35.97     ┆ 134.2     ┆ … ┆ 302.83965 ┆ 120.57522 ┆ 26.607962 ┆ 145.4095 │
│ 5         ┆           ┆           ┆           ┆   ┆ 6046574   ┆ 728913    ┆ 0604584   ┆ 07973118 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## 3. Melt to NeuralForecast long format `(unique_id, ds, y)`

- **`unique_id`** — the original column name (each indicator is its own series)  
- **`ds`** — the date, cast to `datetime` (NeuralForecast requires `datetime64`)  
- **`y`** — the numeric value, cast to `Float64`

In [4]:
# All columns except 'date' are metric series
metric_cols = [c for c in df_wide.columns if c != "date"]

df_long = (
    df_wide
    .melt(
        id_vars="date",
        value_vars=metric_cols,
        variable_name="unique_id",
        value_name="y",
    )
    .rename({"date": "ds"})
    # Cast ds -> Datetime and y -> Float64
    .with_columns([
        pl.col("ds").cast(pl.Datetime("us")),
        pl.col("y").cast(pl.Float64),
    ])
    # NeuralForecast expects columns in this order
    .select(["unique_id", "ds", "y"])
    .sort(["unique_id", "ds"])
)

print(f"Long table shape: {df_long.shape}")
print(f"Number of series: {df_long['unique_id'].n_unique()}")
df_long.head(10)

Long table shape: (358560, 3)
Number of series: 96

/tmp/ipykernel_20433/4264303622.py:6: DeprecationWarning: `DataFrame.melt` is deprecated; use `DataFrame.unpivot` instead, with `index` instead of `id_vars` and `on` instead of `value_vars`
  .melt(

shape: (10, 3)
┌───────────────────────────────┬─────────────────────┬───────┐
│ unique_id                     ┆ ds                  ┆ y     │
│ ---                           ┆ ---                 ┆ ---   │
│ str                           ┆ datetime[μs]        ┆ f64   │
╞═══════════════════════════════╪═════════════════════╪═══════╡
│ fred_automobile_mfg_ppi_value ┆ 2016-01-01 00:00:00 ┆ 149.9 │
│ fred_automobile_mfg_ppi_value ┆ 2016-01-02 00:00:00 ┆ 149.9 │
│ fred_automobile_mfg_ppi_value ┆ 2016-01-03 00:00:00 ┆ 149.9 │
│ fred_automobile_mfg_ppi_value ┆ 2016-01-04 00:00:00 ┆ 149.9 │
│ fred_automobile_mfg_ppi_value ┆ 2016-01-05 00:00:00 ┆ 149.9 │
│ fred_automobile_mfg_ppi_value ┆ 2016-01-06 00:00:00 ┆ 149.9 │
│ fred_automobile_mfg_ppi_value ┆ 2016-01-07 00:00:00 ┆ 149.9 │
│ fred_automobile_mfg_ppi_value ┆ 2016-01-08 00:00:00 ┆ 149.9 │
│ fred_automobile_mfg_ppi_value ┆ 2016-01-09 00:00:00 ┆ 149.9 │
│ fred_automobile_mfg_ppi_value ┆ 2016-01-10 00:00:00 ┆ 149.9 │
└───────────────────────────────┴─────────────────────┴───────┘

## 4. Quick sanity check — series lengths

In [5]:
series_info = (
    df_long
    .group_by("unique_id")
    .agg([
        pl.col("ds").min().alias("start"),
        pl.col("ds").max().alias("end"),
        pl.len().alias("n_obs"),
        pl.col("y").is_null().sum().alias("nulls"),
    ])
    .sort("unique_id")
)

print(series_info)

shape: (96, 5)
┌─────────────────────────────────┬─────────────────────┬─────────────────────┬───────┬───────┐
│ unique_id                       ┆ start               ┆ end                 ┆ n_obs ┆ nulls │
│ ---                             ┆ ---                 ┆ ---                 ┆ ---   ┆ ---   │
│ str                             ┆ datetime[μs]        ┆ datetime[μs]        ┆ u32   ┆ u32   │
╞═════════════════════════════════╪═════════════════════╪═════════════════════╪═══════╪═══════╡
│ fred_automobile_mfg_ppi_value   ┆ 2016-01-01 00:00:00 ┆ 2026-03-23 00:00:00 ┆ 3735  ┆ 0     │
│ fred_crude_oil_prices_wti_dail… ┆ 2016-01-01 00:00:00 ┆ 2026-03-23 00:00:00 ┆ 3735  ┆ 0     │
│ fred_general_freight_trucking_… ┆ 2016-01-01 00:00:00 ┆ 2026-03-23 00:00:00 ┆ 3735  ┆ 0     │
│ fred_metals_and_metal_products… ┆ 2016-01-01 00:00:00 ┆ 2026-03-23 00:00:00 ┆ 3735  ┆ 0     │
│ fred_semiconductor_related_dev… ┆ 2016-01-01 00:00:00 ┆ 2026-03-23 00:00:00 ┆ 3735  ┆ 0     │
│ …                               ┆ …                   ┆ …                   ┆ …     ┆ …     │
│ wb_trade_pct_gdp_mys_value      ┆ 2016-01-01 00:00:00 ┆ 2026-03-23 00:00:00 ┆ 3735  ┆ 0     │
│ wb_trade_pct_gdp_sgp_value      ┆ 2016-01-01 00:00:00 ┆ 2026-03-23 00:00:00 ┆ 3735  ┆ 0     │
│ wb_trade_pct_gdp_tha_value      ┆ 2016-01-01 00:00:00 ┆ 2026-03-23 00:00:00 ┆ 3735  ┆ 0     │
│ wb_trade_pct_gdp_usa_value      ┆ 2016-01-01 00:00:00 ┆ 2026-03-23 00:00:00 ┆ 3735  ┆ 0     │
│ wb_trade_pct_gdp_vnm_value      ┆ 2016-01-01 00:00:00 ┆ 2026-03-23 00:00:00 ┆ 3735  ┆ 0     │
└─────────────────────────────────┴─────────────────────┴─────────────────────┴───────┴───────┘

## 5. (Optional) Convert to pandas for NeuralForecast

NeuralForecast's Python API accepts a **pandas** DataFrame natively.  
If you prefer to work in pandas downstream, run this cell.

In [6]:
df_long_pd = df_long.to_pandas()

# NeuralForecast expects ds as datetime64[ns]
df_long_pd["ds"] = df_long_pd["ds"].astype("datetime64[ns]")

print(df_long_pd.dtypes)
df_long_pd.head()

unique_id               str
ds           datetime64[ns]
y                   float64
dtype: object

                       unique_id         ds      y
0  fred_automobile_mfg_ppi_value 2016-01-01  149.9
1  fred_automobile_mfg_ppi_value 2016-01-02  149.9
2  fred_automobile_mfg_ppi_value 2016-01-03  149.9
3  fred_automobile_mfg_ppi_value 2016-01-04  149.9
4  fred_automobile_mfg_ppi_value 2016-01-05  149.9