In [1]:
"""
Data Pull & Formatting for N-HiTS Time Series Forecasting
==========================================================
Pulls processed data from the supply-chain PostgreSQL database,
resamples everything to a common monthly frequency, pivots each
series into a single wide row per month, then melts into the
NeuralForecast long format: (unique_id, ds, y).

Usable sources (have actual temporal depth):
  - FRED          → monthly economic indicators (already monthly)
  - Polygon       → quarterly corporate financials (upsample to monthly)
  - Census (M3)   → monthly manufacturing survey data

Excluded:
  - OpenSky       → single point-in-time snapshot, no temporal dimension
  - Comtrade      → annual granularity only, too sparse for monthly model
  - WorldBank     → annual granularity only, too sparse for monthly model
"""

import sys
from pathlib import Path

import pandas as pd
import numpy as np

In [2]:
# Add the data_pipeline directory to sys.path so we can import db_utils
sys.path.insert(0, str(Path("").resolve()))

from db_utils import get_engine, test_connection, table_exists

engine = get_engine()
assert test_connection(engine), "Cannot reach PostgreSQL — is the container running?"

2026-03-28 20:34:39 [INFO] db_utils: Creating SQLAlchemy engine: postgresql+psycopg2://admin:***@localhost:5432/supplychain_db
2026-03-28 20:34:39 [INFO] db_utils: Database connection test: OK

In [3]:
# ## 1. Load source tables
# We only pull tables that have real temporal depth.
# OpenSky (snapshot), Comtrade (annual), and WorldBank (annual) are excluded.

# ── FRED: monthly economic indicators ────────────────────────────────────────
fred_df = pd.DataFrame()
if table_exists("processed_fred", engine):
    fred_df = pd.read_sql_table("processed_fred", engine)
    print(f"FRED: {fred_df.shape}")
elif table_exists("raw_fred", engine):
    fred_df = pd.read_sql_table("raw_fred", engine)
    print(f"FRED (raw): {fred_df.shape}")
else:
    print("FRED: table not found — skipping")

FRED: (666, 8)

In [4]:
# ── Polygon: quarterly corporate financials ──────────────────────────────────
polygon_df = pd.DataFrame()
if table_exists("processed_polygon", engine):
    polygon_df = pd.read_sql_table("processed_polygon", engine)
    print(f"Polygon: {polygon_df.shape}")
elif table_exists("raw_polygon", engine):
    polygon_df = pd.read_sql_table("raw_polygon", engine)
    print(f"Polygon (raw): {polygon_df.shape}")
else:
    print("Polygon: table not found — skipping")

Polygon: (781, 22)

In [5]:
# ── Census M3: monthly manufacturing survey ──────────────────────────────────
census_df = pd.DataFrame()
if table_exists("processed_census", engine):
    census_df = pd.read_sql_table("processed_census", engine)
    print(f"Census: {census_df.shape}")
elif table_exists("raw_census", engine):
    census_df = pd.read_sql_table("raw_census", engine)
    print(f"Census (raw): {census_df.shape}")
else:
    print("Census: table not found — skipping")

Census: (278408, 10)

In [6]:
# ## 2. Normalize each source to monthly `(ds, unique_id, y)` long format

monthly_frames: list[pd.DataFrame] = []

In [7]:
# ### 2a. FRED → already monthly
# Each `series_id` becomes a `unique_id`.

if not fred_df.empty:
    fred = fred_df[["series_id", "date", "value"]].copy()
    fred.rename(columns={"date": "ds", "value": "y", "series_id": "unique_id"}, inplace=True)
    fred["ds"] = pd.to_datetime(fred["ds"], errors="coerce")
    fred["y"] = pd.to_numeric(fred["y"], errors="coerce")
    fred.dropna(subset=["ds", "y"], inplace=True)

    # Prefix unique_id so sources don't collide
    fred["unique_id"] = "fred_" + fred["unique_id"].astype(str)

    # Ensure one value per (unique_id, month) — average duplicates
    fred["ds"] = fred["ds"].dt.to_period("M").dt.to_timestamp()
    fred = fred.groupby(["unique_id", "ds"], as_index=False)["y"].mean()

    print(f"FRED series: {fred['unique_id'].nunique()}, rows: {len(fred)}")
    monthly_frames.append(fred)

FRED series: 5, rows: 666

In [8]:
# ### 2b. Polygon → quarterly financials resampled to monthly
# We forward-fill quarterly values across the 3 months of each quarter,
# which is standard for stock-fundamental features.

if not polygon_df.empty:
    # Select key financial metrics to turn into individual series
    value_cols = [
        "revenues", "gross_profit", "net_income_loss", "operating_income_loss",
        "cost_of_revenue", "inventory", "assets", "current_assets",
        "current_liabilities", "liabilities", "net_cash_flow",
        "net_cash_flow_from_operations", "gross_profit_margin",
        "net_profit_margin", "inventory_turnover", "current_ratio",
        "debt_to_assets",
    ]
    # Keep only columns that actually exist
    value_cols = [c for c in value_cols if c in polygon_df.columns]

    poly = polygon_df[["ticker", "end_date"] + value_cols].copy()
    poly["end_date"] = pd.to_datetime(poly["end_date"], errors="coerce")
    poly.dropna(subset=["end_date"], inplace=True)

    # Melt to long format: one row per (ticker, metric, quarter)
    poly_long = poly.melt(
        id_vars=["ticker", "end_date"],
        value_vars=value_cols,
        var_name="metric",
        value_name="y",
    )
    poly_long["y"] = pd.to_numeric(poly_long["y"], errors="coerce")
    poly_long.dropna(subset=["y"], inplace=True)

    poly_long["unique_id"] = "polygon_" + poly_long["ticker"] + "_" + poly_long["metric"]
    poly_long.rename(columns={"end_date": "ds"}, inplace=True)

    # Upsample each series from quarterly → monthly via forward-fill
    resampled_parts = []
    for uid, grp in poly_long.groupby("unique_id"):
        grp = grp.set_index("ds")[["y"]].sort_index()
        grp = grp[~grp.index.duplicated(keep="last")]
        grp = grp.resample("MS").ffill()
        grp["unique_id"] = uid
        grp = grp.reset_index().rename(columns={"index": "ds"})
        if "ds" not in grp.columns:
            grp = grp.rename(columns={grp.columns[0]: "ds"})
        resampled_parts.append(grp)

    if resampled_parts:
        poly_monthly = pd.concat(resampled_parts, ignore_index=True)
        poly_monthly["ds"] = poly_monthly["ds"].dt.to_period("M").dt.to_timestamp()
        print(f"Polygon series: {poly_monthly['unique_id'].nunique()}, rows: {len(poly_monthly)}")
        monthly_frames.append(poly_monthly[["unique_id", "ds", "y"]])

Polygon series: 144, rows: 27828

In [9]:
# ### 2c. Census M3 → already monthly
# We build a `unique_id` from the combination of category, data type, and seasonal adjustment.

if not census_df.empty:
    time_col = "time_slot_date" if "time_slot_date" in census_df.columns else "period_date"
    value_col = "cell_value"

    if time_col in census_df.columns and value_col in census_df.columns:
        cen = census_df.copy()
        cen["ds"] = pd.to_datetime(cen[time_col], errors="coerce")
        cen["y"] = pd.to_numeric(cen[value_col], errors="coerce")
        cen.dropna(subset=["ds", "y"], inplace=True)

        # Build a descriptive unique_id
        id_parts = []
        for col in ["category_code", "data_type_code", "seasonally_adj"]:
            if col in cen.columns:
                id_parts.append(cen[col].astype(str))
        if id_parts:
            cen["unique_id"] = "census_" + id_parts[0]
            for part in id_parts[1:]:
                cen["unique_id"] = cen["unique_id"] + "_" + part
        else:
            cen["unique_id"] = "census_m3"

        cen["ds"] = cen["ds"].dt.to_period("M").dt.to_timestamp()
        cen = cen.groupby(["unique_id", "ds"], as_index=False)["y"].mean()

        print(f"Census series: {cen['unique_id'].nunique()}, rows: {len(cen)}")
        monthly_frames.append(cen[["unique_id", "ds", "y"]])

Census series: 1454, rows: 278408

In [10]:
# ## 3. Merge into a single unified DataFrame

if not monthly_frames:
    raise RuntimeError(
        "No data was loaded from any source! "
        "Make sure the ingestion pipeline has been run and the DB is populated."
    )

ts_df = pd.concat(monthly_frames, ignore_index=True)
ts_df = ts_df.sort_values(["unique_id", "ds"]).reset_index(drop=True)

print(f"\n{'=' * 60}")
print(f"Unified time-series DataFrame")
print(f"  Total rows   : {len(ts_df):,}")
print(f"  Total series  : {ts_df['unique_id'].nunique()}")
print(f"  Date range    : {ts_df['ds'].min()} → {ts_df['ds'].max()}")
print(f"  Columns       : {list(ts_df.columns)}")
print(f"{'=' * 60}")
ts_df.head(10)

============================================================
Unified time-series DataFrame
  Total rows   : 306,902
  Total series  : 1603
  Date range    : 2009-03-01 00:00:00 → 2026-02-01 00:00:00
  Columns       : ['unique_id', 'ds', 'y']
============================================================

             unique_id         ds    y
0  census_11A_MPCTI_no 2010-01-01  0.0
1  census_11A_MPCTI_no 2010-02-01  0.0
2  census_11A_MPCTI_no 2010-03-01  0.0
3  census_11A_MPCTI_no 2010-04-01  0.0
4  census_11A_MPCTI_no 2010-05-01  0.0
5  census_11A_MPCTI_no 2010-06-01  0.0
6  census_11A_MPCTI_no 2010-07-01  0.0
7  census_11A_MPCTI_no 2010-08-01  0.0
8  census_11A_MPCTI_no 2010-09-01  0.0
9  census_11A_MPCTI_no 2010-10-01  0.0

In [15]:
ts_df

                   unique_id         ds             y
0        census_11A_MPCTI_no 2010-01-01  0.000000e+00
1        census_11A_MPCTI_no 2010-02-01  0.000000e+00
2        census_11A_MPCTI_no 2010-03-01  0.000000e+00
3        census_11A_MPCTI_no 2010-04-01  0.000000e+00
4        census_11A_MPCTI_no 2010-05-01  0.000000e+00
...                      ...        ...           ...
306897  polygon_XOM_revenues 2025-08-01  8.150600e+10
306898  polygon_XOM_revenues 2025-09-01  8.150600e+10
306899  polygon_XOM_revenues 2025-10-01  8.529400e+10
306900  polygon_XOM_revenues 2025-11-01  8.529400e+10
306901  polygon_XOM_revenues 2025-12-01  8.529400e+10

[306902 rows x 3 columns]

In [11]:
# ## 4. Quality checks

# Verify zero nulls in the final dataset
null_counts = ts_df.isnull().sum()
print("Null counts per column:")
print(null_counts)
assert null_counts.sum() == 0, f"Found {null_counts.sum()} nulls — investigate before modelling!"

# Show series lengths distribution
series_lengths = ts_df.groupby("unique_id").size()
print(f"\nSeries length stats:\n{series_lengths.describe()}")

# Flag very short series (< 24 months) that may hurt N-HiTS training
short_series = series_lengths[series_lengths < 24]
if not short_series.empty:
    print(f"\n⚠️  {len(short_series)} series have < 24 months of data and may be too short for N-HiTS.")
    print(f"   Consider dropping them or using a shorter input_size.")

Null counts per column:
unique_id      0
ds             0
y            144
dtype: int64

AssertionError: Found 144 nulls — investigate before modelling!

In [12]:
# ## 5. (Optional) Filter to only series with sufficient history

MIN_HISTORY_MONTHS = 24  # at least 2 years of data

series_lens = ts_df.groupby("unique_id").size()
valid_ids = series_lens[series_lens >= MIN_HISTORY_MONTHS].index
ts_df_filtered = ts_df[ts_df["unique_id"].isin(valid_ids)].reset_index(drop=True)

print(f"After filtering (>= {MIN_HISTORY_MONTHS} months):")
print(f"  Series kept : {ts_df_filtered['unique_id'].nunique()} / {ts_df['unique_id'].nunique()}")
print(f"  Rows kept   : {len(ts_df_filtered):,} / {len(ts_df):,}")

After filtering (>= 24 months):
  Series kept : 1599 / 1603
  Rows kept   : 306,894 / 306,902

In [13]:
# ## 6. Ready for N-HiTS
# The `ts_df_filtered` DataFrame is now in the exact format that
# `NeuralForecast` expects: `unique_id`, `ds`, `y`.
#
# ```python
# from neuralforecast import NeuralForecast
# from neuralforecast.models import NHITS
#
# horizon = 12  # 12-month forecast
# models = [NHITS(h=horizon, input_size=2 * horizon, max_steps=500)]
# nf = NeuralForecast(models=models, freq='MS')
# nf.fit(df=ts_df_filtered)
# forecasts = nf.predict()
# ```

# Save to parquet for downstream use
output_path = Path("./parquet/ts_ready.parquet")
ts_df_filtered.to_parquet(output_path, index=False)
print(f"✅ Saved {len(ts_df_filtered):,} rows to {output_path}")

ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - `Import pyarrow` failed. pyarrow is required for parquet support. Use pip or conda to install the pyarrow package.
 - `Import fastparquet` failed. fastparquet is required for parquet support. Use pip or conda to install the fastparquet package.

In [14]:
ts_df_filtered

                   unique_id         ds             y
0        census_11A_MPCTI_no 2010-01-01  0.000000e+00
1        census_11A_MPCTI_no 2010-02-01  0.000000e+00
2        census_11A_MPCTI_no 2010-03-01  0.000000e+00
3        census_11A_MPCTI_no 2010-04-01  0.000000e+00
4        census_11A_MPCTI_no 2010-05-01  0.000000e+00
...                      ...        ...           ...
306889  polygon_XOM_revenues 2025-08-01  8.150600e+10
306890  polygon_XOM_revenues 2025-09-01  8.150600e+10
306891  polygon_XOM_revenues 2025-10-01  8.529400e+10
306892  polygon_XOM_revenues 2025-11-01  8.529400e+10
306893  polygon_XOM_revenues 2025-12-01  8.529400e+10

[306894 rows x 3 columns]